name: On Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build Project
    runs-on: macos-15

    steps:
    - name: Chechout Repository
      uses: actions/checkout@v2

    - name: Select Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '16.0'

    - name: Build
      run: |
        set -o pipefail
        xcodebuild build \
        -scheme unicocheck-ios \
        -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16' \
        -derivedDataPath build \
        | xcpretty

    - name: Archive derived data artifacts
      uses: actions/upload-artifact@v4.4.0
      with:
        name: build
        path: build

  test:
      name: Test Project
      needs: build
      runs-on: macos-15

      steps:
      - name: Chechout Repository
        uses: actions/checkout@v2

      - name: Download derived data artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: build

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Test
        run: |
          set -o pipefail
          xcodebuild build \
          -scheme unicocheck-ios \
          -destination 'platform=iOS Simulator,OS=18.0,name=iPhone 16' \
          -derivedDataPath \
          test
   
    
