name: CI Automated CocoaPod releases

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Publish to CocoaPod register
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push unicocheck-ios.podspec --allow-warnings
