name: On Release

on:
  push:
    branches:
      - main

jobs:
  verify-changed-files:
    runs-on: macos-15

    outputs:
      output1: ${{ steps.changed-files.outputs.modified_files }}

    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
         
  create-tag:
    runs-on: macos-latest
    needs: [verify-changed-files]
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{needs.verify-changed-files.outputs.output1}}
      - name: Is there a change in the unicocheck-ios.podspec? Create tag
        if: contains(needs.verify-changed-files.outputs.output1, 'unicocheck-ios.podspec')
        run: bash scripts/create_github_tag_and_release.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  cocoapods-publish:
    runs-on: macos-latest
    needs: [verify-changed-files, create-tag]
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{needs.verify-changed-files.outputs.output1}}

      - name: Is there a change in the unicocheck-ios.podspec? Publish to CocoaPods
        if: contains(needs.verify-changed-files.outputs.output1, 'unicocheck-ios.podspec')
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push unicocheck-ios.podspec --allow-warnings
